import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const validationDir = "C:\\Users\\Andreatta\\OneDrive - Oracle Corporation\\Andreatta OD\\Pessoal\\A Projetos\\Assistente de Investimento\\Validação Telas";
const reportPath = join(validationDir, "daily-validation-report.json");
const npmAvailable = spawnSync("npm", ["--version"], {
  cwd: root,
  encoding: "utf8",
}).status === 0;

const stages = [
  {
    id: "tests",
    label: "Vitest suite",
    command: "npm test",
    fallback: { command: process.execPath, args: ["node_modules/vitest/vitest.mjs", "run"] },
  },
  {
    id: "build",
    label: "Vite production build",
    command: "npm run build",
    fallback: { command: process.execPath, args: ["node_modules/vite/bin/vite.js", "build"] },
  },
  { id: "screenshots", label: "Screenshots evidence", command: null },
];

function runStage(stage) {
  if (!stage.command) {
    return {
      ...stage,
      status: "manual",
      exitCode: 0,
      note: "Screenshots are generated by the visual validation flow.",
    };
  }

  const startedAt = new Date().toISOString();
  const useFallback = !npmAvailable && stage.fallback;
  const result = useFallback
    ? spawnSync(stage.fallback.command, stage.fallback.args, {
      cwd: root,
      encoding: "utf8",
      stdio: "pipe",
    })
    : spawnSync(stage.command, {
      cwd: root,
      shell: true,
      encoding: "utf8",
      stdio: "pipe",
    });

  return {
    ...stage,
    executedCommand: useFallback ? `${stage.fallback.command} ${stage.fallback.args.join(" ")}` : stage.command,
    status: result.status === 0 ? "passed" : "failed",
    exitCode: result.status ?? 1,
    startedAt,
    finishedAt: new Date().toISOString(),
    stdout: result.stdout,
    stderr: result.stderr,
  };
}

const results = stages.map(runStage);
const failed = results.filter((stage) => stage.status === "failed");
const report = {
  generatedAt: new Date().toISOString(),
  status: failed.length === 0 ? "passed" : "failed",
  stages: results,
};

mkdirSync(validationDir, { recursive: true });
writeFileSync(reportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");

console.log(`Daily validation report written to ${reportPath}`);
for (const stage of results) {
  console.log(`${stage.id}: ${stage.status}${stage.exitCode !== undefined ? ` (${stage.exitCode})` : ""}`);
}

if (failed.length > 0) {
  process.exit(1);
}
