import type {
  CockpitResumo, Decisao, AtivoMercado, FonteDados, TheseEnvelope,
} from "@/types/domain";

const minutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();
const minutesAhead = (m: number) => new Date(Date.now() + m * 60_000).toISOString();

export const mockCockpit = (): CockpitResumo => ({
  tesesTestadas: 1284,
  validacaoHistoricaPct: 0.612,
  expectativaLiquidaMedia: 0.0184,
  tesesAtivas: 7,
  aprendizadosAplicados: 38,
  ultimaAtualizacao: minutesAgo(2),
  frentes: {
    B3:      { ativas: 6, saude: "atualizado",  ultimaIngestaoEm: minutesAgo(2) },
    Cripto:  { ativas: 7, saude: "atualizado",  ultimaIngestaoEm: minutesAgo(0) },
    Imoveis: { ativas: 4, saude: "parcial",     ultimaIngestaoEm: minutesAgo(180) },
  },
});

// ---------- Teses no envelope canônico ----------

export const mockTeses = (): TheseEnvelope[] => [
  {
    id: "t-001",
    front: "b3",
    title: "Reversão técnica em PETR4",
    asset_label: "PETR4",
    hypothesis: "Reversão de curto prazo após exaustão de venda no intradiário com suporte estatístico em 38.20.",
    status: "monitorando",
    opened_at: minutesAgo(120),
    updated_at: minutesAgo(2),
    expected_result_pct: 4.37,
    current_result_pct: 1.82,
    confidence_pct: 71,
    entry_value: 38.42,
    current_value: 39.12,
    target_value: 40.10,
    stop_value: 37.60,
    stop_or_invalidation: "Fechamento abaixo de 37.60 invalida a tese de reversão.",
    suggested_action: "Manter monitoramento",
    learning_note: "",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(2), confidence_in_data_pct: 92 },
    specific: {
      kind: "b3",
      ticker: "PETR4",
      direction: "long",
      evidences: ["RSI saindo de sobrevenda", "Volume crescente na última hora", "Petróleo Brent +1.2%"],
      technicals: [
        { label: "RSI 14", value: "32 → 41", bias: "bull" },
        { label: "MM21", value: "acima", bias: "bull" },
        { label: "MACD", value: "cruzamento+", bias: "bull" },
        { label: "Volume", value: "1.6× média", bias: "bull" },
      ],
      fundamentals: [
        { label: "P/L", value: "4.2", trend: "flat" },
        { label: "DY 12m", value: "11.8%", trend: "up" },
        { label: "ROE", value: "23%", trend: "up" },
        { label: "Dív. Líq./EBITDA", value: "0.9", trend: "down" },
      ],
      news: [
        { title: "Brent sobe 1.2% após corte de produção", source: "Reuters", published_at: minutesAgo(45), sentiment: "positivo" },
        { title: "Petrobras anuncia novo dividendo extraordinário", source: "Valor", published_at: minutesAgo(180), sentiment: "positivo" },
      ],
    },
    completion: {
      is_complete: true, completion_pct: 100, missing_fields: [], pending_items: [],
      next_required_action: "Aguardar próxima janela de avaliação.",
    },
  },
  {
    id: "t-002",
    front: "b3",
    title: "Pressão vendedora em VALE3",
    asset_label: "VALE3",
    hypothesis: "Pressão vendedora pós-divulgação de produção com convergência técnica.",
    status: "confirmando",
    opened_at: minutesAgo(60),
    updated_at: minutesAgo(3),
    expected_result_pct: 2.65,
    current_result_pct: 0.42,
    confidence_pct: 58,
    entry_value: 64.10,
    current_value: 63.83,
    target_value: 62.40,
    stop_value: 65.00,
    stop_or_invalidation: "Recuperação acima de 65.00 com volume invalida a tese.",
    suggested_action: "Aguardar confirmação",
    learning_note: "",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(3), confidence_in_data_pct: 85 },
    specific: {
      kind: "b3",
      ticker: "VALE3",
      direction: "short",
      evidences: ["Rompimento de mínima horária", "Minério -0.8%"],
      technicals: [
        { label: "RSI 14", value: "58 → 49", bias: "bear" },
        { label: "MM21", value: "abaixo", bias: "bear" },
        { label: "Volume", value: "1.1× média", bias: "neutral" },
      ],
      fundamentals: [
        { label: "P/L", value: "5.1", trend: "flat" },
        { label: "DY 12m", value: "8.2%", trend: "down" },
        { label: "Minério 62%", value: "US$ 96/t", trend: "down" },
      ],
      news: [
        { title: "China sinaliza menor demanda por minério no 2T", source: "Bloomberg", published_at: minutesAgo(90), sentiment: "negativo" },
      ],
    },
    completion: {
      is_complete: false, completion_pct: 78,
      missing_fields: ["learning_note"],
      pending_items: ["Confirmação de fluxo institucional"],
      next_required_action: "Aguardar segunda confirmação de gatilho.",
    },
  },
  {
    id: "t-003",
    front: "b3",
    title: "Fluxo institucional em ITUB4",
    asset_label: "ITUB4",
    hypothesis: "Fluxo institucional comprador no setor bancário.",
    status: "validada",
    opened_at: minutesAgo(1440),
    updated_at: minutesAgo(120),
    closed_at: minutesAgo(120),
    expected_result_pct: 3.42,
    current_result_pct: 3.61,
    confidence_pct: 82,
    entry_value: 32.10,
    current_value: 33.26,
    target_value: 33.20,
    stop_value: 31.50,
    stop_or_invalidation: "Perda de 31.50.",
    suggested_action: "Tese encerrada — alvo atingido",
    learning_note: "Padrão de fluxo bancário replicável em janelas de 1-3 dias.",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(120), confidence_in_data_pct: 95 },
    specific: {
      kind: "b3",
      ticker: "ITUB4",
      direction: "long",
      evidences: ["Book agressivo na compra", "Setor bancário +1.1%"],
      technicals: [
        { label: "RSI 14", value: "62", bias: "bull" },
        { label: "MM21", value: "acima", bias: "bull" },
      ],
      fundamentals: [
        { label: "P/L", value: "8.4", trend: "flat" },
        { label: "ROE", value: "21%", trend: "up" },
      ],
      news: [
        { title: "Bancos lideram pregão com fluxo estrangeiro", source: "InfoMoney", published_at: minutesAgo(360), sentiment: "positivo" },
      ],
    },
    completion: {
      is_complete: true, completion_pct: 100, missing_fields: [], pending_items: [],
      next_required_action: "Tese arquivada.",
    },
  },
  {
    id: "t-004",
    front: "b3",
    title: "Repique técnico em MGLU3",
    asset_label: "MGLU3",
    hypothesis: "Repique técnico em zona de suporte.",
    status: "refutada",
    opened_at: minutesAgo(2880),
    updated_at: minutesAgo(1440),
    closed_at: minutesAgo(1440),
    expected_result_pct: 5.6,
    current_result_pct: -3.22,
    confidence_pct: 46,
    entry_value: 12.40,
    current_value: 12.00,
    target_value: 13.10,
    stop_value: 12.00,
    stop_or_invalidation: "Perda do suporte em 12.00.",
    suggested_action: "Tese refutada",
    learning_note: "Suporte semanal isolado sem confirmação de fluxo apresenta baixa taxa de validação (28%).",
    data_quality: { freshness_status: "stale", last_update_at: minutesAgo(1440), confidence_in_data_pct: 60 },
    specific: {
      kind: "b3",
      ticker: "MGLU3",
      direction: "long",
      evidences: ["Suporte semanal", "Sobrevenda diária"],
      technicals: [
        { label: "RSI 14", value: "28", bias: "bull" },
        { label: "MM21", value: "abaixo", bias: "bear" },
      ],
      fundamentals: [
        { label: "P/L", value: "—", trend: "flat" },
        { label: "Margem Líq.", value: "-2.1%", trend: "down" },
      ],
      news: [],
    },
    completion: {
      is_complete: true, completion_pct: 100, missing_fields: [], pending_items: [],
      next_required_action: "Aprendizado já incorporado ao motor.",
    },
  },
  // ---- B3 — range invalidada (rompimento contrário) ----
  {
    id: "t-005",
    front: "b3",
    title: "Range lateral em BBDC4",
    asset_label: "BBDC4",
    hypothesis: "Operação no range 13.80–14.40 com reversão na borda superior.",
    status: "refutada",
    opened_at: minutesAgo(60 * 18),
    updated_at: minutesAgo(60 * 2),
    closed_at: minutesAgo(60 * 2),
    expected_result_pct: 3.1,
    current_result_pct: -2.4,
    confidence_pct: 38,
    entry_value: 14.30,
    current_value: 14.66,
    target_value: 13.95,
    stop_value: 14.55,
    stop_or_invalidation: "Rompimento de 14.55 com volume invalida o range — confirmado.",
    suggested_action: "Tese refutada — range rompido para cima",
    learning_note: "Range em ativo bancário com gatilho macro pendente apresenta baixa taxa de respeito às bordas.",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(60 * 2), confidence_in_data_pct: 88 },
    specific: {
      kind: "b3",
      ticker: "BBDC4",
      direction: "short",
      evidences: ["Rompimento da borda superior", "Volume 1.8× média"],
      technicals: [
        { label: "RSI 14", value: "67", bias: "bull" },
        { label: "MM21", value: "acima", bias: "bull" },
        { label: "Volume", value: "1.8× média", bias: "bull" },
      ],
      fundamentals: [
        { label: "P/L", value: "8.9", trend: "flat" },
        { label: "ROE", value: "16%", trend: "flat" },
      ],
      news: [
        { title: "Bancos sobem após sinalização do Copom", source: "Valor", published_at: minutesAgo(180), sentiment: "positivo" },
      ],
      invalidation_detail: "Fechamento em 14.66 com volume confirma rompimento.",
    },
    completion: {
      is_complete: true, completion_pct: 100, missing_fields: [], pending_items: [],
      next_required_action: "Aprendizado incorporado.",
    },
  },
  // ---- B3 — bearish em atenção, baixa completude e frescor parcial ----
  {
    id: "t-006",
    front: "b3",
    title: "Topo duplo em WEGE3",
    asset_label: "WEGE3",
    hypothesis: "Formação de topo duplo no diário com divergência de RSI.",
    status: "monitorando",
    opened_at: minutesAgo(60 * 30),
    updated_at: minutesAgo(60 * 4),
    expected_result_pct: 6.2,
    current_result_pct: -0.8,
    confidence_pct: 49,
    entry_value: 38.20,
    current_value: 37.90,
    target_value: 35.80,
    stop_value: 39.10,
    stop_or_invalidation: "Fechamento acima de 39.10 invalida o topo duplo.",
    suggested_action: "Atenção — aguardar confirmação do pescoço",
    learning_note: "",
    data_quality: { freshness_status: "partial", last_update_at: minutesAgo(60 * 4), confidence_in_data_pct: 64 },
    specific: {
      kind: "b3",
      ticker: "WEGE3",
      direction: "short",
      evidences: ["Divergência baixista no RSI", "Rejeição na resistência 38.50"],
      technicals: [
        { label: "RSI 14", value: "62 → 54", bias: "bear" },
        { label: "MM21", value: "acima", bias: "neutral" },
        { label: "MACD", value: "perdendo força", bias: "bear" },
      ],
      fundamentals: [
        { label: "P/L", value: "32.1", trend: "flat" },
        { label: "ROE", value: "27%", trend: "flat" },
      ],
      news: [],
    },
    completion: {
      is_complete: false, completion_pct: 62,
      missing_fields: ["learning_note", "fundamentals_completos"],
      pending_items: ["Atualizar fundamentos do último ITR", "Buscar notícias setoriais"],
      next_required_action: "Aguardar perda do pescoço em 37.40.",
    },
  },
  // ---- IMÓVEIS — caso completo ----
  {
    id: "t-im-001",
    front: "imoveis",
    title: "Apto 2dorm para flip — Vila Mariana",
    asset_label: "Vila Mariana · 62m²",
    hypothesis: "Compra abaixo do teto com reforma leve e revenda em 6 meses dentro da banda base de comparáveis.",
    status: "monitorando",
    opened_at: minutesAgo(60 * 24 * 4),
    updated_at: minutesAgo(60 * 6),
    expected_result_pct: 22.5,
    current_result_pct: 0,
    confidence_pct: 74,
    entry_value: 720_000,
    current_value: 720_000,
    target_value: 920_000,
    stop_value: 700_000,
    stop_or_invalidation: "Surgimento de pendência jurídica relevante ou redução de comparáveis abaixo de 880k.",
    suggested_action: "Avançar para visita técnica e validar matrícula",
    learning_note: "Bairro com liquidez consistente em apartamentos de 60-70m².",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(60 * 6), confidence_in_data_pct: 84 },
    specific: {
      kind: "imovel",
      source_url: "https://exemplo.com/imovel/123",
      origin: "OLX + indicação corretor",
      strategy: "flip",
      city: "São Paulo",
      neighborhood: "Vila Mariana",
      property_type: "Apartamento 2 dormitórios",
      imovel_status: "diligencia",
      score_pct: 78,
      next_step: "Agendar visita técnica e solicitar matrícula atualizada",
      asking_price: 740_000,
      appraisal_value: 760_000,
      market_value_estimate: 790_000,
      ceiling_price: 720_000,
      cash_needed: 235_000,
      renovation_budget: 65_000,
      carrying_months: 6,
      monthly_carrying_cost: 2_400,
      sale_comparables_count: 14,
      rent_comparables_count: 9,
      estimated_sale_conservative: 880_000,
      estimated_sale_base: 920_000,
      estimated_sale_optimistic: 970_000,
      estimated_rent_conservative: 3_200,
      roi_estimated_pct: 22.5,
      prazo_estimado_meses: 6,
      accepts_financing: true,
      financing_validated: true,
      diligence: [
        { label: "Matrícula atualizada", state: "pendente", detail: "Solicitada em cartório" },
        { label: "Edital / leilão", state: "ok", detail: "Não se aplica — venda direta" },
        { label: "Dívida de condomínio", state: "ok", detail: "Quitado, declaração assinada" },
        { label: "Dívida de IPTU", state: "ok", detail: "Sem débitos" },
        { label: "Ocupação", state: "ok", detail: "Imóvel desocupado" },
        { label: "Financiamento aceito", state: "ok" },
      ],
      plan_a: "Reforma leve em 8 semanas e listagem em portais com 920k base.",
      plan_b: "Manter 4 meses adicionais e reposicionar com 880k caso liquidez caia.",
      plan_c: "Locação de transição a 3.2k mantendo CDI de carrego.",
      exit_rule: "Descartar se carrying > 9 meses ou queda de 7% no valor base.",
      notes: "Prédio com baixa rotatividade, condomínio 720/mês.",
      analysis: "Spread saudável entre teto (720k) e base de venda (920k) com cushion de 22%.",
      evidences: ["14 comparáveis na faixa 880-960k", "Bairro com DOM médio 38 dias", "Indicador de liquidez alto"],
    },
    completion: {
      is_complete: false, completion_pct: 88,
      missing_fields: ["matricula_validada"],
      pending_items: ["Visita técnica", "Confirmação de matrícula"],
      next_required_action: "Confirmar matrícula em até 5 dias úteis.",
    },
  },
  // ---- IMÓVEIS — caso com muitos campos faltantes ----
  {
    id: "t-im-002",
    front: "imoveis",
    title: "Casa em leilão — Pinheiros (em prospecção)",
    asset_label: "Pinheiros · leilão",
    hypothesis: "Oportunidade preliminar em leilão com potencial de arbitragem; ainda em fase de prospecção.",
    status: "preparando",
    opened_at: minutesAgo(60 * 24 * 1),
    updated_at: minutesAgo(60 * 24),
    expected_result_pct: 0,
    current_result_pct: 0,
    confidence_pct: 32,
    entry_value: 0,
    current_value: 0,
    target_value: 0,
    stop_or_invalidation: "Edital com ônus relevantes ou ocupação irregular invalida a tese.",
    suggested_action: "Coletar edital e matrícula antes de qualquer avaliação",
    learning_note: "",
    data_quality: { freshness_status: "partial", last_update_at: minutesAgo(60 * 24), confidence_in_data_pct: 38 },
    specific: {
      kind: "imovel",
      origin: "Portal de leilões",
      strategy: "arbitragem",
      city: "São Paulo",
      neighborhood: "Pinheiros",
      property_type: "Casa térrea",
      imovel_status: "prospeccao",
      score_pct: 41,
      next_step: "Baixar edital oficial e matrícula",
      asking_price: 480_000,
      // valores ausentes intencionalmente
      diligence: [
        { label: "Matrícula atualizada", state: "faltando" },
        { label: "Edital / leilão", state: "faltando", detail: "Não baixado" },
        { label: "Dívida de condomínio", state: "nao_validado" },
        { label: "Dívida de IPTU", state: "nao_validado" },
        { label: "Ocupação", state: "alerta", detail: "Possível ocupação por terceiros" },
        { label: "Financiamento aceito", state: "nao_validado" },
      ],
      plan_a: "Avaliar viabilidade após leitura do edital.",
      notes: "Tese ainda em prospecção — não usar para decisão.",
    },
    completion: {
      is_complete: false, completion_pct: 34,
      missing_fields: [
        "appraisal_value", "market_value_estimate", "ceiling_price",
        "cash_needed", "renovation_budget", "estimated_sale_base",
        "roi_estimated_pct", "financing_validated",
      ],
      pending_items: ["Baixar edital", "Solicitar matrícula", "Levantar comparáveis"],
      next_required_action: "Baixar o edital e a matrícula para destravar a análise.",
    },
  },
  // ---- IMÓVEIS — em negociação ativa ----
  {
    id: "t-im-003",
    front: "imoveis",
    title: "Sala comercial — Faria Lima (negociação)",
    asset_label: "Faria Lima · 48m²",
    hypothesis: "Aquisição de sala comercial com locação garantida pelo vendedor por 12 meses (sale-leaseback).",
    status: "confirmando",
    opened_at: minutesAgo(60 * 24 * 9),
    updated_at: minutesAgo(60 * 3),
    expected_result_pct: 11.4,
    current_result_pct: 0,
    confidence_pct: 81,
    entry_value: 980_000,
    current_value: 980_000,
    target_value: 1_120_000,
    stop_value: 940_000,
    stop_or_invalidation: "Quebra do contrato de leaseback ou pendência registral relevante invalida a tese.",
    suggested_action: "Enviar contraproposta final em 920k",
    learning_note: "",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(60 * 3), confidence_in_data_pct: 90 },
    specific: {
      kind: "imovel",
      origin: "Indicação direta do proprietário",
      strategy: "renda",
      city: "São Paulo",
      neighborhood: "Itaim Bibi",
      property_type: "Sala comercial",
      imovel_status: "negociacao",
      score_pct: 84,
      next_step: "Formalizar contraproposta e solicitar minuta do leaseback",
      asking_price: 980_000,
      appraisal_value: 1_020_000,
      market_value_estimate: 1_050_000,
      ceiling_price: 940_000,
      cash_needed: 320_000,
      renovation_budget: 0,
      carrying_months: 0,
      monthly_carrying_cost: 1_800,
      sale_comparables_count: 22,
      rent_comparables_count: 18,
      estimated_sale_conservative: 1_080_000,
      estimated_sale_base: 1_120_000,
      estimated_sale_optimistic: 1_180_000,
      estimated_rent_conservative: 7_200,
      roi_estimated_pct: 11.4,
      prazo_estimado_meses: 12,
      accepts_financing: true,
      financing_validated: true,
      diligence: [
        { label: "Matrícula atualizada", state: "ok" },
        { label: "Contrato de leaseback", state: "pendente", detail: "Aguardando minuta do vendedor" },
        { label: "Dívida de condomínio", state: "ok" },
        { label: "Dívida de IPTU", state: "ok" },
        { label: "Ocupação", state: "ok", detail: "Será locada ao próprio vendedor" },
        { label: "Financiamento aceito", state: "ok" },
      ],
      plan_a: "Fechar com leaseback de 12 meses a 7.2k/mês.",
      plan_b: "Sem leaseback: locar via corretora a 6.8k/mês após 60 dias.",
      plan_c: "Revenda em 18 meses na banda base.",
      exit_rule: "Descartar se contraproposta acima de 950k ou minuta de leaseback recusada.",
      notes: "Ativo AAA na região, vacância histórica < 5%.",
      analysis: "Cushion de 40k entre teto e ask, com renda contratada que cobre carrego.",
      evidences: ["22 comparáveis de venda", "18 comparáveis de locação", "Vendedor com urgência declarada"],
    },
    completion: {
      is_complete: false, completion_pct: 92,
      missing_fields: ["minuta_leaseback"],
      pending_items: ["Receber minuta do leaseback"],
      next_required_action: "Solicitar minuta do contrato em até 48h.",
    },
  },
  // ---- IMÓVEIS — descartado ----
  {
    id: "t-im-004",
    front: "imoveis",
    title: "Sobrado — Tatuapé (descartado)",
    asset_label: "Tatuapé · 140m²",
    hypothesis: "Compra para flip com reforma média e revenda em 8 meses.",
    status: "refutada",
    opened_at: minutesAgo(60 * 24 * 14),
    updated_at: minutesAgo(60 * 24 * 2),
    closed_at: minutesAgo(60 * 24 * 2),
    expected_result_pct: 18.0,
    current_result_pct: 0,
    confidence_pct: 22,
    entry_value: 0,
    current_value: 0,
    target_value: 0,
    stop_or_invalidation: "Pendência jurídica em matrícula confirmada — tese descartada.",
    suggested_action: "Tese descartada — risco jurídico inviabiliza flip",
    learning_note: "Sobrados antigos no Tatuapé com inventário em aberto têm taxa de viabilidade < 20%.",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(60 * 24 * 2), confidence_in_data_pct: 80 },
    specific: {
      kind: "imovel",
      origin: "Portal Zap",
      strategy: "flip",
      city: "São Paulo",
      neighborhood: "Tatuapé",
      property_type: "Sobrado 3 dormitórios",
      imovel_status: "descartada",
      score_pct: 28,
      next_step: "Arquivar e registrar aprendizado",
      asking_price: 850_000,
      appraisal_value: 880_000,
      market_value_estimate: 920_000,
      ceiling_price: 780_000,
      sale_comparables_count: 8,
      diligence: [
        { label: "Matrícula atualizada", state: "alerta", detail: "Inventário em aberto há 4 anos" },
        { label: "Dívida de IPTU", state: "alerta", detail: "Dívida ativa de 38k" },
        { label: "Ocupação", state: "ok" },
      ],
      plan_a: "—",
      notes: "Risco jurídico inviabiliza prazo de 8 meses para flip.",
      analysis: "Custo de regularização (~50k) e prazo (~12 meses) corroem o ROI esperado.",
      evidences: ["Matrícula com pendência confirmada", "Cartório estimou 8-14 meses de regularização"],
    },
    completion: {
      is_complete: true, completion_pct: 100, missing_fields: [], pending_items: [],
      next_required_action: "Aprendizado incorporado ao filtro de prospecção.",
    },
  },
];

export const mockMicrotrades = (): TheseEnvelope[] => [
  {
    id: "m-001",
    front: "cripto",
    title: "Sweep + reabsorção BTC 5m",
    asset_label: "BTC/USDT",
    hypothesis: "Reabsorção de liquidez em range de 5min após varredura de stops.",
    status: "monitorando",
    opened_at: minutesAgo(8),
    updated_at: minutesAgo(0),
    expected_result_pct: 0.78,
    current_result_pct: 0.41,
    confidence_pct: 74,
    entry_value: 67_420,
    current_value: 67_697,
    target_value: 67_950,
    stop_value: 67_180,
    stop_or_invalidation: "Perda do range em 67.180 invalida o setup.",
    suggested_action: "Em monitoramento",
    learning_note: "",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(0), confidence_in_data_pct: 96 },
    specific: {
      kind: "microtrade",
      window_min: 25,
      expires_at: minutesAhead(17),
      last_tick_at: minutesAgo(0),
      is_data_delayed: false,
      trigger_pressure_pct: 62,
      evidences: ["Sweep de mínima", "Delta CVD positivo"],
    },
    completion: {
      is_complete: true, completion_pct: 100, missing_fields: [], pending_items: [],
      next_required_action: "Aguardar fechamento da janela.",
    },
  },
  {
    id: "m-002",
    front: "cripto",
    title: "Rejeição em VWAP — ETH 5m",
    asset_label: "ETH/USDT",
    hypothesis: "Rejeição em VWAP horário após teste falho.",
    status: "confirmando",
    opened_at: minutesAgo(3),
    updated_at: minutesAgo(0),
    expected_result_pct: 0.68,
    current_result_pct: -0.11,
    confidence_pct: 61,
    entry_value: 3_512,
    current_value: 3_516,
    target_value: 3_488,
    stop_value: 3_528,
    stop_or_invalidation: "Fechamento de 5min acima de 3.528 invalida a tese.",
    suggested_action: "Aguardando confirmação de fluxo",
    learning_note: "",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(0), confidence_in_data_pct: 90 },
    specific: {
      kind: "microtrade",
      window_min: 15,
      expires_at: minutesAhead(12),
      last_tick_at: minutesAgo(0),
      is_data_delayed: false,
      trigger_pressure_pct: 34,
      evidences: ["Wick em VWAP", "Order flow vendedor"],
    },
    completion: {
      is_complete: false, completion_pct: 82,
      missing_fields: [], pending_items: ["Confirmação de fluxo vendedor"],
      next_required_action: "Aguardar gatilho secundário.",
    },
  },
  {
    id: "m-003",
    front: "cripto",
    title: "Continuação de tendência SOL 5m",
    asset_label: "SOL/USDT",
    hypothesis: "Continuação de tendência intradiária com suporte em média móvel.",
    status: "monitorando",
    opened_at: minutesAgo(22),
    updated_at: minutesAgo(2),
    expected_result_pct: 1.01,
    current_result_pct: 0.92,
    confidence_pct: 69,
    entry_value: 168.40,
    current_value: 169.95,
    target_value: 170.10,
    stop_value: 167.20,
    stop_or_invalidation: "Perda da MM21 em 5min invalida a tese.",
    suggested_action: "Próximo do alvo",
    learning_note: "",
    data_quality: { freshness_status: "partial", last_update_at: minutesAgo(2), confidence_in_data_pct: 70 },
    specific: {
      kind: "microtrade",
      window_min: 40,
      expires_at: minutesAhead(18),
      last_tick_at: minutesAgo(2),
      is_data_delayed: true,
      trigger_pressure_pct: 86,
      evidences: ["Higher lows confirmados", "Volume crescente"],
    },
    completion: {
      is_complete: true, completion_pct: 100, missing_fields: [], pending_items: [],
      next_required_action: "Avaliar parcial no toque do alvo.",
    },
  },
  // ---- preparando: setup desenhado, ainda sem gatilho ----
  {
    id: "m-004",
    front: "cripto",
    title: "Setup de range BTC 5m — preparando",
    asset_label: "BTC/USDT",
    hypothesis: "Aguardando teste da borda inferior do range 67.180–67.950 para entrada long.",
    status: "preparando",
    opened_at: minutesAgo(2),
    updated_at: minutesAgo(0),
    expected_result_pct: 0.92,
    current_result_pct: 0,
    confidence_pct: 55,
    entry_value: 67_200,
    current_value: 67_690,
    target_value: 67_900,
    stop_value: 67_080,
    stop_or_invalidation: "Perda de 67.080 invalida o range.",
    suggested_action: "Aguardando preço atingir zona de gatilho",
    learning_note: "",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(0), confidence_in_data_pct: 95 },
    specific: {
      kind: "microtrade",
      window_min: 30,
      expires_at: minutesAhead(28),
      last_tick_at: minutesAgo(0),
      is_data_delayed: false,
      trigger_pressure_pct: 12,
      evidences: ["Range bem definido nas últimas 6 velas", "Volume médio decrescente"],
      short_thesis_summary: "Long na borda inferior com gatilho ainda não acionado.",
    },
    completion: {
      is_complete: false, completion_pct: 70,
      missing_fields: [], pending_items: ["Aguardar toque na borda inferior"],
      next_required_action: "Aguardar gatilho primário.",
    },
  },
  // ---- gain: alvo atingido, validada ----
  {
    id: "m-005",
    front: "cripto",
    title: "Continuação BNB 5m — alvo atingido",
    asset_label: "BNB/USDT",
    hypothesis: "Continuação de tendência intradiária após pullback em MM21.",
    status: "validada",
    opened_at: minutesAgo(38),
    updated_at: minutesAgo(4),
    closed_at: minutesAgo(4),
    expected_result_pct: 0.85,
    current_result_pct: 0.91,
    confidence_pct: 88,
    entry_value: 612.40,
    current_value: 617.98,
    target_value: 617.60,
    stop_value: 610.10,
    stop_or_invalidation: "Perda de MM21 em 5min invalidaria — não acionado.",
    suggested_action: "Tese encerrada — alvo atingido",
    learning_note: "Pullback em MM21 com volume acima da média mantém taxa de acerto > 70% em janelas curtas.",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(4), confidence_in_data_pct: 96 },
    specific: {
      kind: "microtrade",
      window_min: 45,
      expires_at: minutesAgo(4),
      last_tick_at: minutesAgo(4),
      is_data_delayed: false,
      trigger_pressure_pct: 100,
      evidences: ["Pullback em MM21 confirmado", "Volume 1.4× média", "Alvo atingido em 34min"],
      short_thesis_summary: "Setup clássico de continuação validado.",
    },
    completion: {
      is_complete: true, completion_pct: 100, missing_fields: [], pending_items: [],
      next_required_action: "Aprendizado incorporado.",
    },
  },
  // ---- loss: stop acionado, refutada ----
  {
    id: "m-006",
    front: "cripto",
    title: "Reversão XRP 5m — stop acionado",
    asset_label: "XRP/USDT",
    hypothesis: "Reversão em fundo duplo intradiário com confirmação de volume.",
    status: "refutada",
    opened_at: minutesAgo(26),
    updated_at: minutesAgo(8),
    closed_at: minutesAgo(8),
    expected_result_pct: 1.10,
    current_result_pct: -0.62,
    confidence_pct: 41,
    entry_value: 0.5240,
    current_value: 0.5208,
    target_value: 0.5298,
    stop_value: 0.5208,
    stop_or_invalidation: "Perda de 0.5208 invalida o fundo duplo — confirmado.",
    suggested_action: "Tese refutada — stop acionado",
    learning_note: "Fundo duplo em ativos de baixa cap sem confirmação de book apresenta alta taxa de armadilha.",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(8), confidence_in_data_pct: 92 },
    specific: {
      kind: "microtrade",
      window_min: 30,
      expires_at: minutesAgo(8),
      last_tick_at: minutesAgo(8),
      is_data_delayed: false,
      trigger_pressure_pct: 0,
      evidences: ["Volume não confirmou", "Book vendedor agressivo na entrada", "Stop acionado em 18min"],
      short_thesis_summary: "Setup invalidado por ausência de confirmação de fluxo.",
    },
    completion: {
      is_complete: true, completion_pct: 100, missing_fields: [], pending_items: [],
      next_required_action: "Padrão adicionado ao filtro de baixa confiança.",
    },
  },
  // ---- encerrada por tempo: janela expirou sem gatilho ----
  {
    id: "m-007",
    front: "cripto",
    title: "Setup ADA 5m — janela expirou",
    asset_label: "ADA/USDT",
    hypothesis: "Rompimento de resistência em 0.452 com volume.",
    status: "encerrada_tempo",
    opened_at: minutesAgo(50),
    updated_at: minutesAgo(5),
    closed_at: minutesAgo(5),
    expected_result_pct: 0.95,
    current_result_pct: 0,
    confidence_pct: 48,
    entry_value: 0.4520,
    current_value: 0.4498,
    target_value: 0.4565,
    stop_value: 0.4488,
    stop_or_invalidation: "Janela de 45min sem gatilho — encerrada por tempo.",
    suggested_action: "Tese encerrada — janela expirada sem gatilho",
    learning_note: "Setups de rompimento sem volume crescente nos primeiros 20min raramente disparam.",
    data_quality: { freshness_status: "fresh", last_update_at: minutesAgo(5), confidence_in_data_pct: 90 },
    specific: {
      kind: "microtrade",
      window_min: 45,
      expires_at: minutesAgo(5),
      last_tick_at: minutesAgo(5),
      is_data_delayed: false,
      trigger_pressure_pct: 22,
      evidences: ["Resistência testada 3×", "Volume não acompanhou", "Janela expirou sem gatilho"],
      short_thesis_summary: "Encerrada por tempo sem acionar entrada.",
    },
    completion: {
      is_complete: true, completion_pct: 100, missing_fields: [], pending_items: [],
      next_required_action: "Reanalisar setup em próxima janela se contexto mudar.",
    },
  },
];

export const mockDecisoes = (): Decisao[] => [
  {
    id: "d-001", tipo: "sugestao_tese",
    titulo: "Nova hipótese sugerida em WEGE3",
    resumo: "Padrão de fluxo institucional similar a 12 casos validados anteriormente.",
    criadaEm: minutesAgo(6), status: "pendente", ativoRelacionado: "WEGE3", frente: "B3",
  },
  {
    id: "d-002", tipo: "alerta_revisao",
    titulo: "Revisão sugerida em VALE3",
    resumo: "Confiança da tese caiu de 0.71 para 0.58 nas últimas duas verificações.",
    criadaEm: minutesAgo(18), status: "pendente", ativoRelacionado: "VALE3", frente: "B3",
  },
  {
    id: "d-003", tipo: "confirmacao_hipotese",
    titulo: "Confirmar hipótese em SOL/USDT",
    resumo: "Gatilhos secundários ainda não confirmados. Confirmar manualmente?",
    criadaEm: minutesAgo(2), status: "em_andamento", ativoRelacionado: "SOL/USDT", frente: "Cripto",
  },
  {
    id: "d-004", tipo: "mensagem",
    titulo: "Aprendizado incorporado ao motor",
    resumo: "Padrão refutado em MGLU3 ajustou peso do fator suporte_semanal_isolado para 0.42.",
    criadaEm: minutesAgo(120), status: "concluida",
  },
];

export const mockMercado = (): AtivoMercado[] => [
  { ticker: "IBOV",     nome: "Ibovespa",     frente: "B3",     preco: 132_410, variacao: 0.62, destaque: true },
  { ticker: "PETR4",    nome: "Petrobras",    frente: "B3",     preco: 38.81,   variacao: 1.02, destaque: true },
  { ticker: "VALE3",    nome: "Vale",         frente: "B3",     preco: 64.37,   variacao: -0.41 },
  { ticker: "ITUB4",    nome: "Itaú",         frente: "B3",     preco: 33.16,   variacao: 0.84 },
  { ticker: "BTC/USDT", nome: "Bitcoin",      frente: "Cripto", preco: 67_697,  variacao: 1.20, destaque: true },
  { ticker: "ETH/USDT", nome: "Ethereum",     frente: "Cripto", preco: 3_516,   variacao: -0.18 },
  { ticker: "SOL/USDT", nome: "Solana",       frente: "Cripto", preco: 169.95,  variacao: 2.41 },
  { ticker: "IFIX",     nome: "Índice FIIs",  frente: "Imoveis", preco: 3_240,  variacao: 0.12 },
];

export const mockFontes = (): FonteDados[] => [
  { nome: "B3 — Cotações",        frente: "B3",      ultimaAtualizacao: minutesAgo(2),   saude: "atualizado" },
  { nome: "Binance — Ticks",      frente: "Cripto",  ultimaAtualizacao: minutesAgo(0),   saude: "atualizado" },
  { nome: "FIIs — Boletins CVM",  frente: "Imoveis", ultimaAtualizacao: minutesAgo(180), saude: "parcial"    },
];
